[package]
name = "mindcorpviewer-rust"
version = "1.1.1"
authors = ["autergame"]

[dependencies]
native-dialog = "0.6.3"
byteorder = "1.4.3"
image = "0.24.3"
mime = "0.3.16"
glob = "0.3.0"

gl = "0.14.0"
glam = "0.21.3"
glfw = "0.45.0"
gltf = { version = "1.0.0", features = ["names", "extras", "KHR_materials_unlit"] }

imgui = "0.8.2"
imgui-opengl-renderer = "0.11.1"

serde = { version = "1.0.145", features = ["derive"] }
serde_json = "1.0.85"

[profile]
release = { strip = true }
release-with-debug = { inherits = "release", debug = true }